version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "jakarta.platform:*"
        update-types: ["version-update:semver-major"]
